#!/usr/bin/env bash
set -e -o pipefail

repo_root="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

function buildx_11_buster { # [...docker buildx build flags]: builds multi-arch bstoots/postgres:11.16-buster image
  docker buildx build --platform linux/arm64/v8,linux/amd64 --tag bstoots/postgres:11.16-buster "$repo_root/11/buster" "$@"
}

function build_11_buster { # [...docker buildx build flags]: builds bstoots/postgres:11.16-buster image for only the currect arch
  docker buildx build --tag bstoots/postgres:11.16-buster "$repo_root/11/buster" "$@"
}

function remove_11_buster { # [...docker image rm flags]: removes bstoots/postgres:11.16-buster image
  docker image rm --force bstoots/postgres:11.16-buster "$@"
}

if [[ $# -eq 0 || "$1" == "help" ]]; then
  sed -En 's/^function (.*) \{( #)?/\1/p' "$0"
else
  "$@"
fi
